{
    "name": "Autoinfo Company Knowledge Platform",
    "version": "15.0.1.0.0",
    "category": "Knowledge",
    "summary": "Company knowledge hub with permissions, OCR ingestion, and AI search",
    "license": "LGPL-3",
    "depends": ["mail", "web"],
    "data": [
        "security/knowledge_security.xml",
        "security/knowledge_record_rules.xml",
        "security/ir.model.access.csv",
        "data/knowledge_sequence.xml",
        "data/knowledge_template_data.xml",
        "views/knowledge_item_views.xml",
        "views/knowledge_menu.xml",
        "views/knowledge_taxonomy_views.xml",
        "views/knowledge_template_views.xml",
        "wizard/knowledge_create_from_scan_views.xml",
        "wizard/knowledge_submit_review_views.xml",
        "wizard/knowledge_publish_views.xml",
    ],
    "installable": True,
    "application": True,
}
