from . import knowledge_ai_service
from . import knowledge_attachment
from . import knowledge_department
from . import knowledge_extraction
from . import knowledge_item
from . import knowledge_search_service
from . import knowledge_tag
from . import knowledge_template
from . import knowledge_type
from . import knowledge_version
from . import res_users
